# Generated by Django 5.2.6 on 2026-06-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrinim', '0004_category_alter_product_seller_alter_user_is_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylı kullanıcı mı?'),
        ),
    ]
